apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject-container
        image: yourdockerhubusername/myprojectimage
        ports:
        - containerPort: 3000
